### ISSUE TITLE
貌似需要修改一下数据源了，数据获取不到了。

### ISSUE THREAD

**Issue by hellobiek** [datochan/ctdx#3]
2018/10/10 08:03:50 main.go:38: [Info] 更新基础的股票数据...
2018/10/10 08:03:50 client.go:66: [Error] 创建服务器链接失败,err: dial tcp 121.14.110.200:443: connect: connection refused

**Comment by hellobiek** [comment]
又好了，没事了。

**Comment by datochan** [comment]
通达信的服务器会在每天开市之前的前一个小时左右关闭重启，使用通达信软件也会受到这个影响的。
一般的开市前几分钟都会回复正常，如果需要更改IP，可以在配置文件中更改。
