### ISSUE TITLE
问一个问题，代码中有一段GenerateXXXItem函数，其中的CmdId和EventId是如何获取的。需要什么破解吗？

### ISSUE THREAD

**Issue by hellobiek** [datochan/ctdx#4]
func GenerateStockMinsItem() 
{
    reqNode.CmdId = 0x008D
    reqNode.EventId = 0x0FCD
}

**Comment by datochan** [comment]
哦，这些代码是我分析通达信客户端发现它是硬编码在程序中的，就直接拿来用了。
