### ISSUE TITLE
这次是一晚上都没有连接上数据源，麻烦看下了。有可能的话，麻烦更新下查找数据源的方法，下次可以自己搞定。

### ISSUE THREAD

**Issue by hellobiek** [datochan/ctdx#5]
2019/04/15 18:33:05 main.go:39: [Info] 更新基础的股票数据...
2019/04/15 18:33:05 client.go:70: [Error] 创建服务器链接失败,err: dial tcp 121.14.110.200:443: connect: connection refused
2019/04/15 19:23:12 main.go:39: [Info] 更新基础的股票数据...
2019/04/15 19:23:12 client.go:70: [Error] 创建服务器链接失败,err: dial tcp 121.14.110.200:443: connect: connection refused
2019/04/15 20:13:18 main.go:39: [Info] 更新基础的股票数据...
2019/04/15 20:13:18 client.go:70: [Error] 创建服务器链接失败,err: dial tcp 121.14.110.200:443: connect: connection refused
2019/04/15 21:03:24 main.go:39: [Info] 更新基础的股票数据...
2019/04/15 21:03:24 client.go:70: [Error] 创建服务器链接失败,err: dial tcp 121.14.110.200:443: connect: connection refused
2019/04/15 21:53:30 main.go:39: [Info] 更新基础的股票数据...
2019/04/15 21:53:30 client.go:70: [Error] 创建服务器链接失败,err: dial tcp 121.14.110.200:443: connect: connection refused

**Comment by hellobiek** [comment]
自己电脑上的通达信是海通的，但是换成海通的ip以后，获取失败。
服务器的ip为：115.159.18.59:443

**Comment by datochan** [comment]
换个IP和端口吧，之前的服务器更换了。
比如可以使用: `119.147.171.206:80`
