### ISSUE TITLE
财报数据的获取方式。

### ISSUE THREAD

**Issue by hellobiek** [datochan/ctdx#6]
一直没有注意，财报好几个月没有更新了，最新的是去年9月底的数据。

**Comment by hellobiek** [comment]
我看你已经知道这件事情了，有打算破解新的方法吗？

**Comment by datochan** [comment]
这个不需要新的破解方式的，只是之前为了方便TDX直接通过http的方式获取财报。
现在是将财报的获取方式通过rawsocket的方式传输了。

这个财报一直用了好多年都没变，我公开之后半年就更新了财报的获取方式，我认为这是有针对性的。所以我这次就不明着公开了，有心人总会有办法的~

**Comment by hellobiek** [comment]
方便留个QQ私聊么？我不是官方的人，自己搞了一套量化交易系统，非常需要财报数据。。。。
方便的话，加个QQ呗，我的QQ是295056528.

万分感谢！！！
