### ISSUE TITLE
如果修改的代码量多，我这边可以和你一起搞。

### ISSUE THREAD

**Issue by hellobiek** [datochan/ctdx#7]

**Comment by datochan** [comment]
您好，您这么热心我非常感动~

这个ctdx是从我自己写着玩的cquant项目中提取出来的，只是觉得这部分比较独立，开放出来也是希望能对有需要的人有点儿帮助。目的也主要是用户相互之间的学习交流，甚至都没想过会有人start。

由于我个人原因，空闲时间不多(主要是比较懒)，代码也没专门整理成库的形式，只是将通达信取数据的功能实现出来而已。

如果您真的需要这部分数据的话，可以参考我的另一个项目: [DTGear](https://github.com/datochan/DTGear) 。这个项目是我平常自己用python脚本写的小工具，平常看下数据什么的经常会用到，也会经常更新。

您可以看下您需要的功能，理解了之后整合到您个人的量化系统中就可以了。

至于本项目，我想一般不会继续更新的，最后还是多谢您的关注~
祝您投资愉快！
